/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as VideoVideoIDImport } from './routes/video.$videoID'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const AuthenticatedUploadLazyImport = createFileRoute(
  '/_authenticated/upload',
)()
const AuthenticatedProfileLazyImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedDashboardIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard/',
)()
const AuthenticatedDashboardVideosIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard/videos/',
)()
const AuthenticatedDashboardProfileIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard/profile/',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedUploadLazyRoute = AuthenticatedUploadLazyImport.update({
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/upload.lazy').then((d) => d.Route),
)

const AuthenticatedProfileLazyRoute = AuthenticatedProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/profile.lazy').then((d) => d.Route),
)

const VideoVideoIDRoute = VideoVideoIDImport.update({
  path: '/video/$videoID',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardIndexLazyRoute =
  AuthenticatedDashboardIndexLazyImport.update({
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )

const AuthenticatedDashboardVideosIndexLazyRoute =
  AuthenticatedDashboardVideosIndexLazyImport.update({
    path: '/dashboard/videos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/videos/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardProfileIndexLazyRoute =
  AuthenticatedDashboardProfileIndexLazyImport.update({
    path: '/dashboard/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/profile/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoID': {
      preLoaderRoute: typeof VideoVideoIDImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      preLoaderRoute: typeof AuthenticatedProfileLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/upload': {
      preLoaderRoute: typeof AuthenticatedUploadLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/': {
      preLoaderRoute: typeof AuthenticatedDashboardIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/profile/': {
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/videos/': {
      preLoaderRoute: typeof AuthenticatedDashboardVideosIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedProfileLazyRoute,
    AuthenticatedUploadLazyRoute,
    AuthenticatedDashboardIndexLazyRoute,
    AuthenticatedDashboardProfileIndexLazyRoute,
    AuthenticatedDashboardVideosIndexLazyRoute,
  ]),
  LoginLazyRoute,
  RegisterLazyRoute,
  VideoVideoIDRoute,
])

/* prettier-ignore-end */
